"""initial migration

Revision ID: 28c38e170f52
Revises: 
Create Date: 2024-06-26 23:58:58.094574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c38e170f52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('golf_round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('over_par', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('golf_round')
    op.drop_table('user')
    # ### end Alembic commands ###
