"""Add clubs, errors, and club_errors tables

Revision ID: ab5788518e9a
Revises: 28c38e170f52
Create Date: 2024-06-27 10:32:06.250215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5788518e9a'
down_revision = '28c38e170f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club_error',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('error_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['error_id'], ['error.id'], ),
    sa.PrimaryKeyConstraint('club_id', 'error_id')
    )
    op.drop_table('clubs')
    op.drop_table('club_errors')
    op.drop_table('errors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('errors',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club_errors',
    sa.Column('club_id', sa.INTEGER(), nullable=True),
    sa.Column('error_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['error_id'], ['errors.id'], )
    )
    op.create_table('clubs',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('club_error')
    op.drop_table('error')
    op.drop_table('club')
    # ### end Alembic commands ###
